-- Create interesting_events table
CREATE TABLE interesting_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_name VARCHAR(100) NOT NULL,
    key_of_interest_name VARCHAR(100) NOT NULL,
    key_of_interest_value VARCHAR(500) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index on topic_name for faster lookups
CREATE INDEX idx_interesting_events_topic_name ON interesting_events(topic_name);

-- Create index on created_at for timestamp-based queries
CREATE INDEX idx_interesting_events_created_at ON interesting_events(created_at);

-- Create index on key_of_interest_name for filtering
CREATE INDEX idx_interesting_events_key_name ON interesting_events(key_of_interest_name); 